packages:
  # 应用目录：文档站点、多技术栈测试演示沙箱等
  - 'apps/*'
  # 核心工具与业务组件包目录：存放 CLI、封装请求库、纯逻辑库、UI 库（跨端共用）
  - 'packages/*'
  # # 项目预设模板目录：用于提供 CLI 初始化能力的基础模板（例如 admin, ssr 等）
  # - 'templates/*'
  # 自动化工程规范脚本目录：存放批量重命名、批量发布等 Node 脚本
  - 'scripts'
